[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
division_one_crypto = "D6XYa4oPwgMnVX59YbFLxbYstUYEc2YTddx6xTLY4uRs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet" ## change to "Devnet" for testing on devnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
