[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
division_one_crypto = "D6XYa4oPwgMnVX59YbFLxbYstUYEc2YTddx6xTLY4uRs"

[programs.devnet]
division_one_crypto = "BAnYCRzAkVJSTNiHYZcDnRo8B1e2pSssQwAJEjdEcLbL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet" ## change to "Localnet" for testing on localnet
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
